# Generated by Django 5.0.6 on 2024-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
